### ISSUE TITLE
getting 403 

### ISSUE THREAD

**Issue by a-pikachu** [JohnDoee/rip-avgle#1]
When downloading, the script returns with 

No trailing CRLF found in HTTP header.
[https @ 0x7fecd7700180] HTTP error 403 Forbidden
https://cdn.qooqlevideo.com/key=o42c7A6RU47IqW74yrVQUQ,end=1552030498,limit=2/referer=force,.avgle.com/data=1552030498/media=hlsA/274238.mp4: Server returned 403 Forbidden (access denied)

source path is: https://avgle.com/video/QNM7p7tne7K/%E7%B4%A0%E4%BA%BA%E6%8A%95%E7%A8%BF-%E7%A8%80%E3%81%AB%E8%A6%8B%E3%82%8B%E9%80%B8%E6%9D%90%E3%81%AE%E5%A5%B3%E3%81%AE%E5%AD%90

**Comment by JohnDoee** [comment]
It's because of the captcha, I'm working on a fix that'll allow end-users to solve it.

After it has been solved, it doesn't pop up that often so shouldn't cause major issues.

**Comment by JohnDoee** [comment]
I had to turn it into some GUI stuff to allow for captcha solving but I hope it's acceptable non-the-less.

Check out https://github.com/JohnDoee/rippy
